using UnityEngine;

namespace HeapExplorer
{
    public class RootPath : System.IComparable<RootPath>
    {
        public int count
        {
            get
            {
                return m_Items.Length;
            }
        }

        public RootPathReason reason
        {
            get;
            private set;
        }

        public string reasonString
        {
            get
            {
                switch(reason)
                {
                    case RootPathReason.None:
                        return "";
                    case RootPathReason.AssetBundle:
                        return "this object is an assetbundle, which is never unloaded automatically, but only through an explicit .Unload() call.";
                    case RootPathReason.Component:
                        return "this object is a component, which lives on a gameobject. it will be unloaded on next scene load.";
                    case RootPathReason.GameObject:
                        return "this is a gameobject, that is either part of the loaded scene, or was generated by script. It will be unloaded on next scene load if nobody is referencing it";
                    case RootPathReason.UnityManager:
                        return "this is an internal unity'manager' style object, which is a global object that will never be unloaded";
                    case RootPathReason.DontUnloadUnusedAsset:
                        return "the DontUnloadUnusedAsset hideflag is set on this object. Unity's builtin resources set this flag. Users can also set the flag themselves";
                    case RootPathReason.DontDestroyOnLoad:
                        return "DontDestroyOnLoad() was called on this object, so it will never be unloaded";
                    case RootPathReason.Static:
                        return "Static fields are global variables. Anything they reference will not be unloaded.";
                    case RootPathReason.Unknown:
                        return "This object is a root, but the memory profiler UI does not yet understand why";
                }

                return "???";
            }
        }

        ObjectProxy[] m_Items = new ObjectProxy[0];

        public RootPath(RootPathReason reason, ObjectProxy[] path)
            : base()
        {
            this.reason = reason;
            this.m_Items = path;
        }

        public ObjectProxy this[int index]
        {
            get
            {
                return m_Items[index];
            }
        }

        public int CompareTo(RootPath other)
        {
            var x = ((long)reason << 40) + Mathf.Max(0, int.MaxValue - count);
            var y = ((long)other.reason << 40) + Mathf.Max(0, int.MaxValue - other.count);
            return y.CompareTo(x);
        }
    }
}
